//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorySync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>c:\MyProgramms\Test\DirectorySync\Left\bin</string>
  <string>c:\MyProgramms\Test\DirectorySync\Left\deploy</string>
  <string>c:\MyProgramms\Test\DirectorySync\Left\obj</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LeftDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LeftDirectories"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>c:\MyProgramms\Test\DirectorySync\Right\bin</string>
  <string>c:\MyProgramms\Test\DirectorySync\Right\deploy</string>
  <string>c:\MyProgramms\Test\DirectorySync\Right\obj</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RightDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RightDirectories"]));
            }
        }
    }
}
